sudo: true
language: node_js
node_js:
  - 10.0
  - 12.0
services:
  - xvfb
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=google-chrome-stable
  - export DISPLAY=:99.0
script:
  - npm run lint
  - karma start --single-run
